# Numpy exercises

นายณัฐวัฒน์ วีรเดชทวีวรรณ  65070083

1. นำเข้า numpy package และตั้งชื่อว่า np 

In [3]:
import numpy as np

2. สร้าง vector ที่มีค่า 0 ขนาดความยาว 10 หน่วย

In [4]:
ans = np.zeros(10, dtype=int)
print(ans)

[0 0 0 0 0 0 0 0 0 0]


3. สร้าง vector ที่มีค่า 0 ขนาดความยาว 10 หน่วย และกำหนดให้สมาชิกตัวที่ 5 มีค่าเท่ากับ 1

In [4]:
ans = np.zeros(10, dtype=int)
ans[4] = 1
print(ans)

[0 0 0 0 1 0 0 0 0 0]


4. สร้าง vector เก็บค่าตัวเลขตั้งแต่ 12-51

In [5]:
ans = np.arange(12,52)
print(ans)

[12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33 34 35
 36 37 38 39 40 41 42 43 44 45 46 47 48 49 50 51]


5. ทำการสลับลำดับของสมาชิกภายใน vector ที่สร้างขึ้นจากข้อก่อนหน้า (สมาชิกตัวแรก เป็นตัวสุดท้าย ตามลำดับ)

In [6]:
rev = ans[::-1]
print(rev)

[51 50 49 48 47 46 45 44 43 42 41 40 39 38 37 36 35 34 33 32 31 30 29 28
 27 26 25 24 23 22 21 20 19 18 17 16 15 14 13 12]


6. สร้าง array ขนาด 3x3 ที่เก็บค่าตั้งแต่ 0-8

In [26]:
ans = np.arange(9).reshape(3,3)
print(ans)

[[0 1 2]
 [3 4 5]
 [6 7 8]]


7. จงหาตำแหน่ง (index) ของสมาชิกที่มีค่าเท่ากับ 0 ภายใน array [5,-8,0,0,2,0]

In [7]:
arr = np.array([5,-8,0,0,2,0])
print(np.where(arr==0))

(array([2, 3, 5], dtype=int64),)


8. จงสร้าง 3x3 identity matrix

In [8]:
ans = np.eye(3,3)
print(ans)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


9. จงสร้าง 3x3x3 array ของตัวเลขแบบสุ่ม

In [9]:
ans = np.random.randint(100, size=(3,3,3))
print(ans)

[[[49 13 13]
  [19 46 89]
  [79 11 21]]

 [[96 19 12]
  [37 84 65]
  [70  4 64]]

 [[60 77 52]
  [48 28 19]
  [ 7 63 66]]]


10. จงสร้าง array ขนาด 10x10 ของตัวเลขแบบสุ่ม และแสดงผลค่าตัวเลขที่มากที่สุดและน้อยที่สุดตามลำดับ

In [41]:
ans = np.random.randint(100, size=(10,10))
print(ans)
print(ans.max())
print(ans.min())

[[97 93 69 14 12 55 78 18 66 83]
 [13  1 12 26 53 98 35 90 81 35]
 [74 64 29  3 56 29 94 57 23 81]
 [48 23 58 96 21  8  6  2 28 55]
 [63 87 74  9 60 49 71 36 51 63]
 [70 60 23 50 37 54 88 23 85 30]
 [91 31 15  6 16 93 89 26 61 16]
 [18 67 81 11 21 61 73 27 36 69]
 [ 5 88 38 11 47  0 74 32 60 48]
 [ 8 55 71  3 60 20  3 75 27  3]]
98
0


11. สร้าง Vector ของตัวเลขแบบสุ่มที่มีความยาว 40 หน่วย และแสดงผลค่าเฉลี่ยของชุดตัวเลขดังกล่าว

In [10]:
ans = np.random.randint(100, size=40)
print(ans)
print(ans.mean())

[46 71 52 12 66 83  1 66 57 49 20 77 39 84 71 45 68  7 77 28 25 10 49 76
 37 44 68 30 20 32 27 72 98 19 77 39  4 33 18 66]
46.575


12. สร้าง array ขนาด 5x5 โดยกำหนดตัวเลขบริเวณขอบมีค่าเท่ากับ 1 และตัวเลขอื่นๆ มีค่าเท่ากับ 0

In [11]:
ans = np.zeros((5,5))
ans[0] = 1
ans[4] = 1
ans[:,0] = 1
ans[:,4] = 1
print(ans)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


13. เพิ่มขอบ (pad) ขนาด 1 หน่วยของ array จากข้อก่อนหน้า โดยกำหนดให้สมาชิกในขอบดังกล่าว มีค่าเท่ากับ 0

In [12]:
ans = np.zeros((7,7))
ans[1] = 1
ans[5] = 1
ans[:,1] = 1
ans[:,5] = 1
ans[0] = 0
ans[6] = 0
ans[:,0] = 0
ans[:,6] = 0
print(ans)

[[0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 0. 0. 0. 1. 0.]
 [0. 1. 1. 1. 1. 1. 0.]
 [0. 0. 0. 0. 0. 0. 0.]]


14. สร้าง array ขนาด 5x5 โดยกำหนดให้สมาชิกในแนวทะแยงมีค่าเท่ากับ 1,2,3,4,5 และสมาชิกตำแหน่งอื่นๆ มีค่าเท่ากับ 0

In [13]:
ans = np.eye(5,5, dtype=int)
for i in range(5):
    for j in range(5):
        if i == j and i > 0 and j > 0:
            ans[i,j] += i
print(ans)

[[1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]
 [0 0 0 0 5]]


15. สร้างของตัวเลข array ขนาด 8x8 โดยกำหนดให้สมาชิกใน array มีค่าเท่ากับ 0 และ 1 สลับกันไป (Checkboard pattern)

In [14]:
ans = np.zeros((8,8), dtype=int)
for i in range(8):
    for j in range(8):
        if (i + j) % 2 == 0:
            pass
        else:
            ans[i,j] = 1
print(ans)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


16. กำหนดให้ output คือ array ของตัวเลขแบบสุ่ม ขนาด (4,5,6) จงหาค่าตำแหน่ง (Index) ของสมาชิกตัวที่ 32

In [15]:
ans = np.random.randint(100, size=(4,5,6))
print(ans)
print(ans[1,0,2])

[[[54  6 65 43 86 69]
  [ 2 27 53 55 41 61]
  [89 92 36 78 48 64]
  [87 31 12 67 94 54]
  [ 0 90 44 22 85 93]]

 [[56 24 61 62 46 52]
  [81 43  3 80 38  2]
  [30 41 69  7 69 27]
  [77 29 53 74 51  9]
  [79 64 84 11 19 69]]

 [[17 44 73 52 26 17]
  [85 90 48 84 76 60]
  [19 24 51 39 50 71]
  [29 89 81 86 31 65]
  [55 95 14 77 67 77]]

 [[44 43 29 69 59 68]
  [51 56 77 31 99 48]
  [46 99 32 11 59 29]
  [64 56 87 58 13 98]
  [61 33 45 52  1 40]]]
61


17. สร้าง Checkboard array ขนาด 10x10 โดยใช้ฟังก์ชัน tile (https://numpy.org/doc/stable/reference/generated/numpy.tile.html)

In [16]:
ans = np.array([[0,1],[1,0]])
ans = np.tile(ans,(5,5))
print(ans)

[[0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0 1 0]]


18. สร้าง vector ของตัวเลขแบบสุ่มความยาว 10 หน่วยและทำการเรียงลำดับจากน้อยไปมาก

In [17]:
ans = np.random.randint(100, size=10)
ans.sort()
print(ans)

[10 13 17 25 28 46 49 57 79 84]


19. สร้าง vector ของตัวเลขแบบสุ่มความยาว 10 หน่วยและทำการเรียงลำดับจากมากไปน้อย

In [18]:
ans = np.random.randint(100, size=10)
ans.sort()
print(ans[::-1])

[85 80 78 55 50 47 30 23  9  4]


20. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะหลักจากน้อยไปมาก

In [19]:
ans = np.random.randint(100, size=(10,2))
ans.sort(axis=0)
print(ans)

[[12  5]
 [29 19]
 [31 22]
 [33 28]
 [39 30]
 [44 32]
 [69 37]
 [69 67]
 [73 79]
 [98 97]]


21. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะหลักจากมากไปน้อย

In [20]:
ans = np.random.randint(100, size=(10,2))
ans.sort(axis=0)
print(ans[::-1])

[[84 73]
 [73 67]
 [71 65]
 [58 60]
 [48 57]
 [32 51]
 [22 47]
 [17 39]
 [16 29]
 [ 5  2]]


22. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะแถวจากน้อยไปมาก

In [21]:
ans = np.random.randint(100, size=(10,2))
ans.sort(axis=1)
print(ans)

[[ 9 48]
 [25 30]
 [26 86]
 [50 82]
 [22 55]
 [26 88]
 [46 81]
 [57 80]
 [58 61]
 [22 80]]


23. สร้าง array ขนาด 10x2 ของตัวเลขแบบสุ่ม ทำการเรียงลำดับตัวเลขในแต่ล่ะแถวจากมากไปน้อย

In [22]:
ans = np.random.randint(100, size=(10,2))
ans.sort(axis=1)
print(ans[::,::-1])

[[42 40]
 [53 15]
 [97 30]
 [68  4]
 [35  4]
 [94 66]
 [27 15]
 [49 47]
 [17  2]
 [62 15]]


24. สร้าง array ของตัวเลขแบบสุ่มขนาด 10x2 จำนวน 2 อันและนำมาต่อกันให้ได้ array ผลลัพธ์ขนาด 20*2

In [23]:
arr_1 = np.random.randint(100, size=(10,2))
arr_2 = np.random.randint(100, size=(10,2))
ans = np.concatenate((arr_1,arr_2), axis=0)
print(ans)

[[19  0]
 [28 13]
 [49 52]
 [45 91]
 [ 6 55]
 [25 18]
 [52 59]
 [64 92]
 [69 89]
 [80 84]
 [82 72]
 [18 90]
 [98 35]
 [68 84]
 [ 6 26]
 [84 94]
 [78 68]
 [21 12]
 [79 80]
 [20 37]]


25. สร้าง array ของตัวเลขแบบสุ่มขนาด 10x2 จำนวน 2 อันและนำมาต่อกันให้ได้ array ผลลัพธ์ขนาด 10*4

In [24]:
arr_1 = np.random.randint(100, size=(10,2))
arr_2 = np.random.randint(100, size=(10,2))
ans = np.concatenate((arr_1,arr_2), axis=1)
print(ans)

[[58 51 91 65]
 [78 92 12  5]
 [58 62 73 36]
 [96 61 72 43]
 [34 97 29 86]
 [60 86 28 66]
 [ 7 17 21 54]
 [38 49 55 86]
 [40 75 57 72]
 [78 40 88 60]]


26.สร้าง array ขนาด (3,) ของ [('apple', 256), ('oragne', 124), ('banana', 924)] กำหนดให้ ข้อมูลในแต่ล่ะหลัก มีชื่อว่า name และ pid ตามลำดับ พร้อมทั้งกำหนด data type ของข้อมูล คือ ข้อความและตัวเลขตามลำดับ และเรียงลำดับข้อมูลตามชื่อผลไม้ (ในหลักแรก) ตามตัวอักษร

In [25]:
col_name = np.dtype([('name','U100'),('pid','int64')])
fruits = np.array([('apple', 256), ('oragne', 124), ('banana', 924)], dtype=col_name)
ans = np.sort(fruits, order='name')
print(ans)

[('apple', 256) ('banana', 924) ('oragne', 124)]


27.สร้าง array ขนาด (3,) ของ [('apple', 256), ('oragne', 124), ('banana', 924)] กำหนดให้ ข้อมูลในแต่ล่ะหลัก มีชื่อว่า name และ pid ตามลำดับ พร้อมทั้งกำหนด data type ของข้อมูล คือ ข้อความและตัวเลขตามลำดับ และเรียงลำดับข้อมูลตามรหัสสินค้า (ในหลักที่สอง) จากมากไปน้อย

In [26]:
col_name = np.dtype([('name','U100'),('pid','int64')])
fruits = np.array([('apple', 256), ('oragne', 124), ('banana', 924)], dtype=col_name)
ans = np.sort(fruits, order='pid')
print(ans[::-1])

[('banana', 924) ('apple', 256) ('oragne', 124)]


28. สร้าง array ขนาด 3*2 ของ [['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]] และเรียงลำดับข้อมูลตามชื่อผลไม้ (ในหลักแรก) ตามตัวอักษร

In [26]:
fruits_lis = np.array([['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]])
col_name = np.dtype([('name','U100'),('pid',np.float16)])
fruits_tup = []
for i in range(fruits_lis.shape[0]):
    fruits_tup.append(tuple(fruits_lis[i]))
fruits_tup = np.array(fruits_tup, dtype=col_name)
ans = np.sort(fruits_tup, order='name')
print(ans)

[('apple',  2.56) ('banana',  9.24) ('oragne', -1.24)]


29. สร้าง array ขนาด 3*2 ของ [['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]] และเรียงลำดับข้อมูลตามราคา (ในหลักที่ 2) จากมากไปน้อย

In [29]:
fruits_lis = np.array([['apple', 2.56], ['oragne', -1.24], ['banana', 9.24]])
col_name = np.dtype([('name','U100'),('pid',np.float16)])
fruits_tup = []
for i in range(fruits_lis.shape[0]):
    fruits_tup.append(tuple(fruits_lis[i]))
fruits_tup = np.array(fruits_tup, dtype=col_name)
ans = np.sort(fruits_tup, order='pid')[::-1]
print(ans)

[('banana',  9.24) ('apple',  2.56) ('oragne', -1.24)]


30.สร้าง vector ของตัวเลขแบบสุ่มในช่วง 1-10 จำนวน 100 ตัวเลข และแสดงความถี่ของตัวเลขแต่ล่ะตัวภายใน vector

In [28]:
ans = np.random.randint(1,11,100)
print(ans)
for num in range(10):
    print("เลข", num + 1, "=", len(ans[ans == num + 1]), "ตัว")

[10  6  1  1  1  8  5  2  1  1  7  7  3  4  8  3  8  8  6  3  5  3  1  5
  7  2  8  4  2  8  3  4  4 10 10  4  9  3  1  5  6  1 10  3  9 10  8  7
  3  5  1  7  5  4  7  2  7  1  2  8  5 10  1  2  2  7  3  2  5  2  4  8
  9  3  1  9  7  1  2  7  4 10  5  1  4  2  4  3  2  8  2  3  3  8  3  8
  5  9  8  3]
เลข 1 = 14 ตัว
เลข 2 = 13 ตัว
เลข 3 = 15 ตัว
เลข 4 = 10 ตัว
เลข 5 = 10 ตัว
เลข 6 = 3 ตัว
เลข 7 = 10 ตัว
เลข 8 = 13 ตัว
เลข 9 = 5 ตัว
เลข 10 = 7 ตัว


31. สร้าง $3\times3$ Matrix และ ทำการ Transpose

$matrix = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{bmatrix}$

$matrix\_transpose = \begin{bmatrix}1 & 2 & 3\\4 & 5 & 6\\7 & 8 & 9\end{bmatrix}^{\ \ \intercal} = \begin{bmatrix}1 & 4 & 7\\2 & 5 & 8\\3 & 6 & 9\end{bmatrix}$

In [30]:
ans = np.arange(1,10)
ans = ans.reshape(3,3)
ans = ans.transpose()
print(ans)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


32. จากข้อมูลในข้อ 17 จงเปลี่ยนรูปแบบให้อยู่ในรูป 1xN Array

In [29]:
ans = np.array([[0,1],[1,0]])
ans = np.tile(ans,(5,5))
print(ans.flatten())

[0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1
 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0
 1 0 1 0 1 0 0 1 0 1 0 1 0 1 0 1 1 0 1 0 1 0 1 0 1 0]


33. ทำการหา inverse ของ 
$matrix = \begin{bmatrix}1 & 2\\3 & 4\end{bmatrix}$

In [5]:
ans = np.array([[1,2],[3,4]])
invert = np.linalg.inv(ans)
print(invert)

[[-2.   1. ]
 [ 1.5 -0.5]]


34. สร้าง Array 1x10 ที่เก็บข้อมูลน้ำหนัก และ Array 1x10 ที่เก็บข้อมูลความสูงของนักศึกษา จำนวน 100 คน โดย ข้อมูลน้ำหนักให้ทำการสุ่มตัวเลขในช่วง 45 - 90 และ ข้อมูลความสูงให้ทำการสุ่มข้อมูลในช่วง 150 - 180

<center>$BMI = \frac{Weight\ (kg)}{Height^2\ (m)}\ \ \ \ \ \ \ \ \ \ \ \ \ \ $</center>

34.1) จงหาจำนวนนักเรียนที่มีค่า BMI เกิน 22

34.2) จงหาค่า Mean, Median, Standard Deviation ของค่า BMI

In [9]:
weight = np.random.randint(45,91, size=(1,100))
high = np.random.randint(150,181, size=(1,100))
bmi = weight / ((high / 100) ** 2)
print("34.1) จำนวนนักเรียนที่มีค่าBMIเกิน22 = %d คน" %len(bmi[bmi > 22]))
print("34.2) ค่าMeanของค่าBMI = %f" %np.mean(bmi))
print("34.2) ค่าMeadianของค่าBMI = %f" %np.median(bmi))
print("34.2) ค่าStandard Deviationของค่าBMI = %f" %np.std(bmi))

34.1) จำนวนนักเรียนที่มีค่าBMIเกิน22 = 65 คน
34.2) ค่าMeanของค่าBMI = 25.178023
34.2) ค่าMeadianของค่าBMI = 24.535124
34.2) ค่าStandard Deviationของค่าBMI = 5.593178


35. สร้าง Array ค่าคะแนนของนักศึกษาโดยการสุ่มตัวเลขในช่วง 0 - 100 จำนวน 100 ค่า และ ทำการจำแนกเกรดของนักศึกษาตามตารางด้านล่าง

| Grade | Point | Score |
| --- | --- | --- |
| A | 4.0 | >=80 |
| B+ | 3.5 | >=75 |
| B | 3.0 | >=70 |
| C+ | 2.5 | >=65 |
| C | 2.0 | >=60 |
| D+ | 1.5 | >=55 |
| D | 1.0 | >=50 |
| F | 0.0 | <50 |

EX.

 $scores = \begin{bmatrix}10 & 50 & 40 & 60 & 75 & 100\end{bmatrix}$ //ตัวอย่างข้อมูล
 
 $answer = \begin{bmatrix}F & D & F & C & B+ & A\end{bmatrix}$ //คำตอบ

In [31]:
scores = np.random.randint(101, size=100)
print("A :", scores[scores >= 80])
scores = scores[scores < 80]
print("B+ :", scores[75 <= scores])
scores = scores[scores < 75]
print("B :", scores[70 <= scores])
scores = scores[scores < 70]
print("C+ :", scores[65 <= scores])
scores = scores[scores < 65]
print("C :", scores[60 <= scores])
scores = scores[scores < 60]
print("D+ :", scores[55 <= scores])
scores = scores[scores < 55]
print("D :", scores[50 <= scores])
print("F :", scores[scores < 50])

A : [ 97  96  87  98 100  91  91  81  89  95  91  93  83  97  89  82  93  88
  93]
B+ : [76 79 77]
B : [73 70 71 71 73 74]
C+ : [65 69 69]
C : [64 64]
D+ : [58 55 58 57 55]
D : [53 52 51 54 53]
F : [36 46 33 38 43 31 43 15 17 44 38 45 46 24 21 40 32  7  1 27 14 22 42 38
 20  3 38 49 24 41 39 48  4 33 26  6 25  1 38  4  8 22  0  2 40 36  6  7
  8 39 29  2 34 33 47 39  8]
